# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVZAwwj9KXQlmUZx9uApVWGh6NV1OXb0
"""

resposta = input('deseja ir a próxima tela')
if resposta == 'sim':
  print('Vcocê foi para outra tela')
else:
  print('Você saiu do sistema')

nome = input('Informe o nome de usuário: ')
sexo = input("Informea 'F' para feminino e 'M' para masculino: ").upper()
if(sexo == 'M'):
    sexo = 'o'
elif(sexo == 'F'):
     sexo = 'a'
usuario = int(input('Informe o tipo de usuario \n 1 - para administrador \n 2 - para usuario comum \n 3 para membro associado'))
if(usuario == 1):
    usuario = 'administrador do sistema'
elif(usuario == 3):
    usuario = 'membro associado'
elif (lokusuario ==2):
    usuario = 'usuario comum'
else:
    usuario = 'usuario não resistente'
print(f'Seja bem vind{sexo} {nome}, a sua licença e de {usuario}')